- name: Change owner in home dir {{ main_user }}
  ansible.builtin.file:
    path: "/home/{{ main_user }}"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    recurse: yes
    state: directory